"""Initial rename tables

Revision ID: d28b858adf9c
Revises: 
Create Date: 2026-01-11 18:30:50.662144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28b858adf9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jagdamba_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jagdamba_contact_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jagdamba_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jagdamba_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jagdamba_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_jagdamba_user_username'), ['username'], unique=True)

    op.create_table('jagdamba_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['jagdamba_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jagdamba_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('fabric_type', sa.String(length=64), nullable=True),
    sa.Column('width', sa.String(length=32), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['jagdamba_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jagdamba_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jagdamba_product_name'), ['name'], unique=False)

    op.create_table('jagdamba_product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=64), nullable=False),
    sa.Column('hex_code', sa.String(length=16), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['jagdamba_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jagdamba_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['jagdamba_order.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['jagdamba_product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category')
    op.drop_table('order_item')
    op.drop_table('product_variant')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('contact_message')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))

    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_address', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('base_price', sa.FLOAT(), nullable=False),
    sa.Column('fabric_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('width', sa.VARCHAR(length=32), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)

    op.create_table('contact_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    op.create_table('product_variant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('color_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('hex_code', sa.VARCHAR(length=16), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=256), nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_variant_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price_at_purchase', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('jagdamba_order_item')
    op.drop_table('jagdamba_product_variant')
    with op.batch_alter_table('jagdamba_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jagdamba_product_name'))

    op.drop_table('jagdamba_product')
    op.drop_table('jagdamba_order')
    with op.batch_alter_table('jagdamba_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jagdamba_user_username'))
        batch_op.drop_index(batch_op.f('ix_jagdamba_user_email'))

    op.drop_table('jagdamba_user')
    op.drop_table('jagdamba_contact_message')
    op.drop_table('jagdamba_category')
    # ### end Alembic commands ###
